---
title: 데이터 변환
tags: data
sidebar:
  nav: docs-en
---

데이터 분석을 위해서는 원래 데이터 값을 그대로 사용하는 것보다는 적절한 형태로 변환을 해야 하는 경우가 종종 있습니다. 
데이터 변환도 데이터의 종류가 무엇이냐에 따라서 사용할 수 있는 방법이 차이가 납니다.

명목형 데이터의 경우 가장 간단한 방법은 One-Hot Encoding을 사용하는 것입니다.

In [1]:
import pandas as pd
df = pd.read_csv('data/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
pd.get_dummies(df['Sex'])

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

기존 컬럼은 삭제하고 One-Hot Encoding된 컬럼을 추가하려면 아래와 같이 하면 됩니다.

In [4]:
pd.get_dummies(df, columns=['Sex'])

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,1,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,1,0
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,0,1
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,0,1

또는 아래와 같이 Contingency Table을 만들 수 있습니다.

In [17]:
pd.crosstab(index=df['Sex'], columns=df['Embarked'])

Embarked   C   Q    S
Sex
female    73  36  203
male      95  41  441

수치형 데이터의 경우는 정규화를 사용합니다. 만약 regression 문제를 푼다면 가능한 feature들의 값의 범위를 맞추는 것이 좋습니다. 그렇지 않으면 값이 큰 feature에 너무 크게 영향을 받게 됩니다.

In [10]:
from sklearn.preprocessing import MinMaxScaler

# Age와 Fare의 최소값은 -1, 최대값은 1이 되도록 변환
mms = MinMaxScaler(feature_range=(-1, 1))
df[['Age_n', 'Fare_n']] = mms.fit_transform(df[['Age', 'Fare']])

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Age_n,Fare_n
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,714.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,-0.264159,-0.874283
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,0.365079,0.193990
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,-1.000000,-1.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,-0.504775,-0.969120
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,-0.306861,-0.943575
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,-0.055542,-0.878984
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000

In [12]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
df[['Age_s', 'Fare_s']] = ss.fit_transform(df[['Age', 'Fare']])

In [15]:
df.describe()[['Age', 'Fare', 'Age_s', 'Fare_s']]

              Age        Fare         Age_s        Fare_s
count  714.000000  891.000000  7.140000e+02  8.910000e+02
mean    29.699118   32.204208  2.388379e-16  3.987333e-18
std     14.526497   49.693429  1.000701e+00  1.000562e+00
min      0.420000    0.000000 -2.016979e+00 -6.484217e-01
25%     20.125000    7.910400 -6.595416e-01 -4.891482e-01
50%     28.000000   14.454200 -1.170488e-01 -3.573909e-01
75%     38.000000   31.000000  5.718310e-01 -2.424635e-02
max     80.000000  512.329200  3.465126e+00  9.667167e+00